### ISSUE TITLE
Won't run with a rescue

### ISSUE THREAD

**Issue by SpencerBlum** [learn-co-curriculum/ruby-metaprogramming-triangle-classification-lab#1]
The code only runs completely with the rescue commented out. 

<img width="494" alt="Screen Shot 2020-02-26 at 2 08 40 PM" src="https://user-images.githubusercontent.com/15002278/75378389-93bf7b00-58a1-11ea-982d-9262a5104262.png">

**Comment by lizbur10** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved. Note, however, that if you are working in Canvas the changes may not show up right away.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
